/**
 * Компактные сид-словари (топ частотных слов) для построения trie на лету.
 * Полные словари (до 30k слов на язык) добавляются tools/build-dicts.mjs
 * в chrome.storage.local; этот файл — гарантированный минимум, чтобы
 * расширение работало сразу после установки без сети.
 * Формат: слова через пробел, только нижний регистр.
 */
(function (root) {
  'use strict';
  const LF = root.LayoutFix;
  if (LF.DICT_DATA) return;

  // prettier-ignore
  LF.DICT_DATA = {
    ru: 'и в не на я быть что он с как а то все она так его но да ты к у же вы за бы по только ее мне было вот от меня еще нет о из ему теперь когда даже ну вдруг ли если уже или ни был него до вас нибудь опять уж вам сказал ведь там потом себя ничего ей может они тут где есть надо ней для мы тебя их чем была сам чтоб без будто человек чего раз тоже себе под жизнь будет ж тогда кто этот говорил того потому этого какой совсем ним здесь этом один почти мой тем чтобы нее кажется сейчас были куда зачем сказать всех никогда сегодня можно при наконец два другой хоть после над больше тот через эти нас про всего них какая много разве три эту моя впрочем хорошо свою этой перед иногда лучше чуть том нельзя такой им более всегда конечно всю между дом привет спасибо пока здравствуйте помоги пожалуйста работа время день год человек дело жизнь рука слово место часть неделя глаз вопрос сторона страна мир друг сила',
    en: 'the be to of and a in that have i it for not on with he as you do at this but his by from they we say her she or an will my one all would there their what so up out if about who get which go me when make can like time no just him know take people into year your good some could them see other than then now look only come its over think also back after use two how our work first well way even new want because any these give day most us is are was were been has had did said each may find where much before right too means old same tell set three state never become between high really something both those always show large often together asked house world going school important until form food keep children feet land side without boy once animal life enough took four head above kind began almost live page got earth need far hand year mother light country father let night picture being study second soon story since white ever paper hard near sentence better best across during today however sure knew try told young sun thing whole hear example heard several change answer room sea against top turned learn point city play toward five himself usually money seen car morning hello world thanks',
    ukr: 'і в не на я бути що він з як а то все вона так його але да ти до у же ви за б по тільки її мені було ось від мене ще нема про із йому тепер коли навіть ну раптом чи якщо вже або ні був до вас щось знову вам сказав бо там потім себе нічого їй може вони тут де треба неї для ми тебе їх чим була сам щоб без ніби людина чого раз також собі під життя буде ж тоді хто цей говорив того тому цього який зовсім ним цьому один майже мій тим здається зараз були куди навіщо сказати всіх ніколи сьогодні можна при нарешті два інший хоч після над більше той через ці нас всього них яка багато хіба три цю моя втім добре свою цій перед іноді краще трохи тому не можна такий їм більш завжди звісно всю між дім привіт дякую будь ласка робота час день рік людина справа життя рука слово місце частина тиждень око питання сторона країна світ друг сила',
    by: 'і в не на я быць што ён з як а то ўсе яна так яго але ты да у ж вы за б па толькі яе мне было вось ад мяне яшчэ няма пра із яму цяпер калі нават ну раптам ці калі ўжо або ні быў да вас нешта зноў вам сказаў бо там потым сябе нічога ёй можа яны тут дзе трэба яй для мы цябе іх чым была сам каб без нібы чалавек чаго раз таксама сабе пад жыццё будзе ж тады хто гэты казаў таго таму гэтага які зусім ім гэтым адзін амаль мой тым яе здаецца былі куды навошта сказаць усіх ніколи сёння можна пры нарэшце два іншы хоць пасля над больш той праз гэтыя нас ўсяго іх які шмат ці тры гэтую мая аднак добра сваю гэтай перад часам лепш крыху таму нельга такі ім болей заўсёды канешне ўсю паміж дом прывітанне дзякуй пакуль працы час дзень год чалавек справа жыццё рука слова месца частка тыдзень вока пытанне бок краіна свет сіла',
    de: 'der die und in den von zu das mit sich des auf für ist im dem nicht ein eine als auch es an werden aus er hat dass sie nach wird bei einer um am sind noch wie einem über einen so zum war haben nur oder aber vor zur bis mehr schon alle wenn kann würde was ich bin du mein mir mich wir unser ihr euch ihren denn doch sehr hier da ja nein bitte danke guten morgen tag abend tschüss hallo arbeit zeit jahr mensch sache leben hand wort ort teil woche auge frage seite land welt freund kraft klein groß neu alt jung gut schlecht schön haus lesen schreiben zählen gehen kommen nehmen geben sehen hören sprechen arbeiten denken lieben warten anfangen beenden öffnen schließen',
    fr: 'le la les un une des du de et est être qui que dans pour pas sur plus avec tout par mais nous vous ils elles ce cette ces son ses leur leurs mon ma mes ton ta tes notre nos votre vos il elle on ne se sa là ou où comme si quand donc alors très bien merci bonjour bonsoir salut au revoir oui non travail temps jour année personne chose vie main mot lieu partie semaine œil question côté pays monde ami force petit grand nouveau vieux jeune bon mauvais beau maison école lire écrire compter aller venir prendre donner voir entendre parler travailler penser aimer attendre commencer finir ouvrir fermer',
    es: 'el la los las un una unos unas de del al y o pero si no más por para con sin sobre entre desde hasta según durante como cuando donde quien cual qué cómo cuánto muy bien gracias buenos días buenas tardes noches adiós hola sí trabajo tiempo día año persona cosa vida mano palabra lugar parte semana ojo pregunta lado país mundo amigo fuerza pequeño grande nuevo viejo joven ser estar tener hacer poder decir ir ver dar saber querer llegar pasar deber poner parecer quedar creer hablar llevar dejar seguir encontrar llamar venir pensar salir volver tomar conocer vivir sentir bueno malo bonito casa escuela leer escribir contar ir venir tomar dar ver oír hablar trabajar pensar amar esperar empezar terminar abrir cerrar',
    it: 'il lo la i gli le un uno una di del della dei delle a al alla ai agli da dal dalla in nel nella con col su sul sulla per tra fra e o ma se no più senza sopra durante come quando dove chi quale che cosa quanto molto bene grazie buongiorno buonasera arrivederci ciao sì lavoro tempo giorno anno persona cosa vita mano parola luogo parte settimana occhio domanda lato paese mondo amico forza piccolo grande nuovo vecchio giovane buono cattivo bello casa scuola leggere scrivere contare andare venire prendere dare vedere sentire parlare lavorare pensare amare aspettare cominciare finire aprire chiudere',
    pl: 'nie być na że on ja się tak jego ale do jak już ty to za by ją mnie była jeszcze nie ma o z nim teraz kiedy nawet dobrze nagle czy jeśli albo ani był go was coś znowu pan powiedział bo tam potem siebie nic jej może oni tu gdzie trzeba dla my ciebie ich czym sam żeby bez jakby człowiek czego raz też sobie pod życie będzie wtedy kto ten mówił dlatego jaki zupełnie tu tym jeden prawie mój żeby wydaje teraz były dokąd po co powiedzieć wszystkich nigdy dzisiaj można przy wreszcie dwa inny choć nad więcej przez te nas całości nich jaka dużo trzy tę moją jednak dobrze swoją tej przed czasem lepiej trochę temu taki im bardziej zawsze oczywiście całą między dom dzień dziękuję cześć pracy czas rok człowiek sprawa życie ręka słowo miejsce część tydzień oko pytanie strona kraj świat przyjaciel siła',
    tr: 'bir ve bu için da de ile o ben sen biz siz onlar ne ki çok ama gibi var yok daha en olarak ise diye kadar sonra önce şimdi hep zaten yani nasıl neden hangi kim nerede ne zaman şey gün yıl insan hayat el söz yer parça hafta göz soru taraf dünya ülke arkadaş güç küçük büyük yeni eski genç iyi kötü güzel ev iş okumak yazmak saymak gitmek gelmek almak vermek bakmak dinlemek konuşmak çalışmak düşünmek sevmek beklemek başlamak bitirmek açmak kapatmak merhaba günaydın iyi akşamlar hoşça kal teşekkür ederim lütfen evet hayır üzgünüm affedersiniz rica ederim sağ ol',
    he: 'של לא עם על זה גם אבל כל היא הוא אני אתה אתם אתן מה כמו יש אין יותר רק אולי כן תודה בבקשה שלום להתראות בוקר טוב ערב לילה עבודה זמן יום שנה אדם דבר חיים יד מילה מקום חלק שבוע עין שאלה צד ארץ עולם חבר כוח קטן גדול חדש ישן צעיר רע יפה בית ספר לקרוא לכתוב לספור ללכת לבוא לקחת לתת לראות לשמוע לדבר לעבוד לחשוב לאהוב לחכות להתחיל לסיים לפתוח לסגור',
    ar: 'في من على أن هذا أيضا لكن كل هي هو أنا أنت أنتم ما مثل يوجد أكثر فقط ربما نعم شكرا فضلك سلام مع السلامة صباح مساء ليل سعيد عمل وقت يوم سنة إنسان شيء حياة يد كلمة مكان جزء أسبوع عين سؤال جهة بلد عالم صديق قوة صغير كبير جديد قديم شاب جيد سيء جميل بيت مدرسة اقرأ اكتب احسب اذهب تعال خذ أعط انظر اسمع تكلم اعمل فكر أحب انتظر ابدأ أنه افتح أغلق'
  };
})(typeof self !== 'undefined' ? self : globalThis);
